# Generated by Django 4.2 on 2023-06-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('collage_name', models.CharField(max_length=100)),
                ('parent_number', models.IntegerField()),
                ('parent_email', models.EmailField(max_length=254)),
                ('student_email', models.EmailField(max_length=254)),
                ('percentage', models.IntegerField()),
                ('practical_mark', models.IntegerField()),
                ('extra_act_mark', models.IntegerField()),
            ],
        ),
    ]
